services:
  redis:
    image: redis:latest
    container_name: orbit-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: >
      /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"

  caddy:
    image: caddy:2-alpine
    container_name: orbit-caddy
    restart: unless-stopped
    command: ["caddy", "run", "--config", "/etc/caddy/caddy.json"]
    environment:
      - CADDY_ON_DEMAND_ASK=${CADDY_ON_DEMAND_ASK}
      - ACME_EMAIL=${ACME_EMAIL}
      - ZEROSSL_API_KEY=${ZEROSSL_API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:2019:2019"
    volumes:
      - ./caddy.json:/etc/caddy/caddy.json
      - caddy-data:/data
      - caddy-config:/config

  buildkit:
    image: moby/buildkit:latest
    container_name: buildkit
    restart: unless-stopped
    privileged: true
    volumes:
      - buildkit-data:/var/lib/buildkit

volumes:
  redis-data:
  caddy-data:
  caddy-config:
  buildkit-data:
